### ISSUE TITLE
Fix broken example

### ISSUE THREAD

**Issue by theabm** [pdidev/deisa#3]
The toy problem in `example/derivative.py` does not work because the Deisa API has been modified and the example has not been updated accordingly. 

The current signature for Deisa initialization is:
``` python
def __init__(self, scheduler_info, nb_workers: int, use_ucx=False):
```
while in `derivative.py` Deisa is being initialized with a wrong second argument:
``` python
scheduler_info = 'scheduler.json'
config_file = 'config.yml'

# Initialize Deisa
Deisa = Deisa(scheduler_info, config_file)
```

**Comment by theabm** [comment]
Commit 24a0b3f2d64a6a1b58c894b99b52bbdb4136adf5 closes this issue.

**Comment by jbigot** [comment]
Nice! Thanks
